import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/components/layout/Navbar";
import TailwindIndicator from "@/components/layout/tailwind-indicator";
import MotionProvider from "@/components/layout/framer-motion/MotionProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ClearLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <MotionProvider>
        <body className={cn(inter.className, "overflow-x-hidden")}>
          <div className='container mx-auto pt-10 lg:max-w-6xl'>
            <Navbar />
            {children}
          </div>
          <TailwindIndicator />
        </body>
      </MotionProvider>
    </html>
  );
}
